#!/bin/sh
# Install the mastersoft statusline wrapper.
#
# Drops a tiny script at ~/.local/bin/mastersoft-statusline that resolves
# the latest installed plugin version at runtime. Settings.json can then
# point to a stable path — no need to update it when the plugin bumps.
#
# Idempotent. Re-run anytime.

set -eu

BIN_DIR="$HOME/.local/bin"
WRAPPER="$BIN_DIR/mastersoft-statusline"

mkdir -p "$BIN_DIR"

cat > "$WRAPPER" <<'WRAPPER_EOF'
#!/bin/sh
# Auto-generated by mastersoft install-statusline.sh.
# Resolves latest installed plugin version and execs statusline.js.
SCRIPT=$(ls -d "$HOME/.claude/plugins/cache/mastersoft/mastersoft/"*/hooks/statusline.js 2>/dev/null | sort -V | tail -n 1)
[ -z "$SCRIPT" ] && exit 0
exec node "$SCRIPT" "$@"
WRAPPER_EOF

chmod +x "$WRAPPER"

printf '\033[32m✓\033[0m wrapper installed at %s\n' "$WRAPPER"
echo

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *)
    printf '\033[33m⚠\033[0m  %s not in PATH. Add to your shell rc:\n' "$BIN_DIR"
    echo '    export PATH="$HOME/.local/bin:$PATH"'
    echo
    ;;
esac

echo 'Add this block to ~/.claude/settings.json:'
echo
cat <<'JSON_EOF'
  "statusLine": {
    "type": "command",
    "command": "mastersoft-statusline",
    "padding": 0
  }
JSON_EOF
echo
echo 'Then reload: /reload-plugins (or restart Claude Code).'
